### ISSUE TITLE
Other player using Greatblade causes client to crash

### ISSUE THREAD

**Issue by yakisobadayo** [jsburger/Clash#1]
I've been using this mod on my server and I love it! However I seem to have come across an issue where when another player swings a greatblade, my game crashes:

[crash-2024-06-09_00.35.11-client.txt](https://github.com/user-attachments/files/15783620/crash-2024-06-09_00.35.11-client.txt)

**Comment by jsburger** [comment]
I think I know what the problem is. I'll see if I can't get a new build out later today.

**Comment by jsburger** [comment]
I have uploaded a new build to curseforge. It might take a few days to get approved since it is the weekend. Let me know if the issue is resolved.

**Comment by yakisobadayo** [comment]
I've been testing on my server and it seems to be working perfectly now! Thanks so much!
